// Code generated by protoc-gen-go.
// source: ping.proto
// DO NOT EDIT!

/*
Package ping is a generated protocol buffer package.

It is generated from these files:
	ping.proto

It has these top-level messages:
	Ping
*/
package ping

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Ping struct {
	Header           *common.Header `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	Timestamp        *int64         `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}

func (m *Ping) GetHeader() *common.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Ping) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}
