// Code generated by protoc-gen-go.
// source: fighting.proto
// DO NOT EDIT!

/*
Package fighting is a generated protocol buffer package.

It is generated from these files:
	fighting.proto

It has these top-level messages:
*/
package fighting

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
