// Code generated by protoc-gen-go.
// source: building.proto
// DO NOT EDIT!

/*
Package building is a generated protocol buffer package.

It is generated from these files:
	building.proto

It has these top-level messages:
*/
package building

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
